SDHB-Server-App/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => :registrations
  resources :users

  resources :emergency_notifications

  post 'emergency_notifications' => 'emergency_notifications#create'
  post 'emergency_notifications_group' => 'emergency_notifications#createGroup'
  post 'emergency_notifications_region' => 'emergency_notifications#createRegion'
  post 'users/registerID' => 'users#registerID'
  post 'emergency_notifications/countSuccess' => 'emergency_notifications#countSuccess'

  get 'emergency_notifications/index'
  get 'allusers' => 'users#index'
  get 'authenticate_users' => 'users#authenticate'
  get 'allnotifications' => 'emergency_notifications#list'
  get 'emergency_notifications_group' => 'emergency_notifications#group'
  get 'emergency_notifications_region' => 'emergency_notifications#region'
  get 'delete_all' => 'emergency_notifications#clear_notifications'

  root 'emergency_notifications#index'

end

SDHB-Server-App/app/models/user.rb
class User < ActiveRecord::Base
end

SDHB-Server-App/app/models/users.rb
class Users < ActiveRecord::Base
end

SDHB-Server-App/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, :except => ["registerID"]
  skip_before_action :verify_authenticity_token

  # GET /users
  # GET /users.json
  def authenticate
    @users = User.all
  end
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allusers
  # PATCH/PUT /allusers.json
  def update
	@user.update(user_params)
	redirect_to :action => 'index'
  end
  
  # POST /users/registerID
  # POST /users/registerID.json
  #----------------Method for registering the ID------------------------------------------------------------------------
  def registerID
	p "POST successful"
	#render :text => params[:staffID, :lastName, :firstName, :region, :registrationID]
	user = User.create(staffID: params[:staffID], lastName: params[:lastName], firstName: params[:firstName], deviceID: params[:registrationID], authenticated: false, region: params[:region], group: 1)
  end
  #---------------------------------------------------------------------------------------------------------------------
  

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:staffID, :lastName, :firstName, :deviceID, :authenticated, :region, :group)
    end
end

SDHB-Server-App/app/helpers/users_helper.rb
module UsersHelper
end

SDHB-Server-App/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group" id="inputbox">
    <%= f.label :staffID, :class => "input-group-addon" %>
    <%= f.text_field :staffID, :class => "form-control" %>
  </div>
  <br>
  <div  class="input-group" id="inputbox">
    <%= f.label :lastName, :class => "input-group-addon" %>
    <%= f.text_field :lastName, :class => "form-control" %>
  </div>
  <br>
  <div class="input-group" id="inputbox">
    <%= f.label :firstName, :class => "input-group-addon" %>
    <%= f.text_field :firstName, :class => "form-control" %>
  </div>
  <br>
  <div class="input-group" id="inputbox">
    <%= f.label :deviceID, :class => "input-group-addon" %>
    <%= f.text_field :deviceID, :class => "form-control" %>
  </div>
  <br>
  <div class="input-group" id="inputbox">
    <%= f.label :authenticated, :class => "input-group-addon" %>
    <%= f.text_field :authenticated, :class => "form-control" %>
  </div>
  <br>
  <div class="input-group" id="inputbox">
    <%= f.label :region, :class => "input-group-addon" %>
    <%= f.text_field :region, :class => "form-control" %>
  </div>
  <br>
  <div class="input-group" id="inputbox">
    <%= f.label :group, :class => "input-group-addon" %>
    <%= f.number_field :group, :class => "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary"%>
  </div>
<% end %>

SDHB-Server-App/app/views/users/authenticate.html.erb
<!--ALL USERS VIEW-->
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title>All Users</title>
	</head>
	<body>
		<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/emergency_notifications_group">Send Group Notification</a>
					</li>
					<li>
						<a href="/emergency_notifications_region">Send Region Notification</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
					<li>
						<a href="/allnotifications">Previous Notifications</a>
					</li>
					<li>
						<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>
					</li>
				</ul>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
			<h1 class="jumbotron">Authenticate users</h1>

			<table class="table table-striped">
			  <thead>
				<tr>
				  <th>Staffid</th>
				  <th>Lastname</th>
				  <th>Firstname</th>
				  <th>Deviceid</th>
				  <th>Authenticated</th>
				  <th>Region</th>
				  <th>Group</th>
				  <th colspan="3"></th>
				</tr>
			  </thead>
			  <tbody>
				<% @users.each do |user| %>
				  <tr>
					<td><%= user.staffID %></td>
					<td><%= user.lastName %></td>
					<td><%= user.firstName %></td>
					<td><div id="deviceID"><%= user.deviceID %></div></td>
					<td><%= user.authenticated %></td>
					<td><%= user.region %></td>
					<td><%= user.group %></td>
					<td><%= link_to 'Edit', edit_user_path(user) %></td>
					<td><%= link_to 'Delete User', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				  </tr>
				<% end %>
			  </tbody>
			</table>

			<!-- /#page-content-wrapper -->

		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}

		});
		</script>
	</body>
</html>

SDHB-Server-App/app/views/users/edit.html.erb
<!--EDIT USER VIEW-->
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title>All Users</title>
	</head>
	<body>
		<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/emergency_notifications_group">Send Group Notification</a>
					</li>
					<li>
						<a href="/emergency_notifications_region">Send Region Notification</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
					<li>
						<a href="/allnotifications">Previous Notifications</a>
					</li>
					<li>
						<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>
					</li>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
			<h1 class="jumbotron">Edit User</h1>
			<%= render 'form' %>
			<!-- /#page-content-wrapper -->
		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}

		});
		</script>
	</body>
</html>

SDHB-Server-App/app/views/users/index.html.erb
<!--ALL USERS VIEW-->
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title>All Users</title>
	</head>
	<body>
		<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/emergency_notifications_group">Send Group Notification</a>
					</li>
					<li>
						<a href="/emergency_notifications_region">Send Region Notification</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
					<li>
						<a href="/allnotifications">Previous Notifications</a>
					</li>
					<li>
						<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>
					</li>
				</ul>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
			<h1 class="jumbotron">Listing users</h1>
			<table class="table table-striped">
			  <thead>
				<tr>
				  <th>Staffid</th>
				  <th>Lastname</th>
				  <th>Firstname</th>
				  <th>Deviceid</th>
				  <th>Authenticated</th>
				  <th>Region</th>
				  <th>Group</th>
				  <th colspan="3"></th>
				</tr>
			  </thead>
			  <tbody>
				<% @users.each do |user| %>
				  <tr>
					<td><%= user.staffID %></td>
					<td><%= user.lastName %></td>
					<td><%= user.firstName %></td>
					<td><div id="deviceID"><%= user.deviceID %></div></td>
					<td>
						<% if user.authenticated? %>
						  <%= form_for user do |f| %>
							<%= f.check_box :authenticated, value: false %>
							<%= f.submit 'Update' %>
						  <% end %>
						  <% else %>
						  <%= form_for user do |f| %>
							<%= f.check_box :authenticated, value: true %>
							<%= f.submit 'Update' %>
						  <% end %>
						<% end %>
					</td>
					<td><%= user.region %></td>
					<td><%= user.group %></td>
					<td><%= link_to 'Edit', edit_user_path(user) %></td>
					<td><%= link_to 'Delete User', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				  </tr>
				<% end %>
			  </tbody>
			</table>
			<br>

			<!-- /#page-content-wrapper -->

		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}

		});
		</script>
	</body>
</html>

SDHB-Server-App/app/views/users/new.html.erb
<!--EDIT USER VIEW-->
<html>
	<head>
		<title>Edit User</title>
	</head>
	<body>
	<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
				<h1 class="jumbotron">Edit User</h1>
				<!--New Users Form-->
				<form action="/users" method="POST" class="form-horizontal">
					<h3>User Details</h3>
					<br>
					<!--Staff ID-->
					<div class="input-group" id="staffID">
						<span class="input-group-addon" id="sizing-addon1">Staff ID</span>
						<input type="text" name="user[staffID]" class="form-control" placeholder="xxxxxx" aria-describedby="sizing-addon1">
					</div>
					<br>
					<!--Last Name-->
					<div class="input-group" id="lastName">
						<span class="input-group-addon" id="sizing-addon1">Last Name</span>
						<input type="text" name="user[lastName]" class="form-control" placeholder="" aria-describedby="sizing-addon1">
					</div>
			</div>
			<!-- /#page-content-wrapper -->
		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}
			
		});
		</script>
	</body>
</html>

SDHB-Server-App/app/views/users/show.html.erb
<!--AFTER UPDATE VIEW-->
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title>All Users</title>
	</head>
	<body>
		<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/emergency_notifications_group">Send Group Notification</a>
					</li>
					<li>
						<a href="/emergency_notifications_region">Send Region Notification</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
					<li>
						<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>
					</li>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
			<h1 class="jumbotron">Listing users</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Staffid:</strong>
  <%= @user.staffID %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastName %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstName %>
</p>

<p>
  <strong>Deviceid:</strong>
  <%= @user.deviceID %>
</p>

<p>
  <strong>Authenticated:</strong>
  <%= @user.authenticated %>
</p>

<p>
  <strong>Region:</strong>
  <%= @user.region %>
</p>

<p>
  <strong>Group:</strong>
  <%= @user.group %>
</p>

<!-- /#page-content-wrapper -->

		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}

		});
		</script>
	</body>
</html>