SDHB-Server-App/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => :registrations
  resources :users

  resources :emergency_notifications

  post 'emergency_notifications' => 'emergency_notifications#create'
  post 'emergency_notifications_group' => 'emergency_notifications#createGroup'
  post 'emergency_notifications_region' => 'emergency_notifications#createRegion'
  post 'users/registerID' => 'users#registerID'
  post 'emergency_notifications/countSuccess' => 'emergency_notifications#countSuccess'

  get 'emergency_notifications/index'
  get 'allusers' => 'users#index'
  get 'authenticate_users' => 'users#authenticate'
  get 'allnotifications' => 'emergency_notifications#list'
  get 'emergency_notifications_group' => 'emergency_notifications#group'
  get 'emergency_notifications_region' => 'emergency_notifications#region'
  get 'delete_all' => 'emergency_notifications#clear_notifications'

  root 'emergency_notifications#index'

end

SDHB-Server-App/app/models/emergency_notification.rb
class EmergencyNotification < ActiveRecord::Base
end

SDHB-Server-App/app/controllers/emergency_notifications_controller.rb
class EmergencyNotificationsController < ApplicationController
  before_action :set_emergency_notification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, :except => ["countSuccess"]
  skip_before_action :verify_authenticity_token

  # GET /emergency_notifications
  # GET /emergency_notifications.json
  def index
    @emergency_notifications = EmergencyNotification.all
  end

  # GET /emergency_notifications/1
  # GET /emergency_notifications/1.json
  def show
  end

  # GET /emergency_notifications/new
  def new
    @emergency_notification = EmergencyNotification.new
  end

  # GET /emergency_notifications/1/edit
  def edit
  end

  # GET /clear_notifications
  def clear_notifications
    #Delete everything in the notifications table
    EmergencyNotification.delete_all
    #redirect back to the all notifications view
	  redirect_to :action => 'list'
  end

  # POST /emergency_notifications
  # POST /emergency_notifications.json
  def create
    #create new Notification with parameters passed in
    @emergency_notification = EmergencyNotification.new(emergency_notification_params)
    #print notification details to logs and console for debug purposes
  	logger.error(@emergency_notification.message)
  	logger.error(@emergency_notification.title)
    #save notification
    @emergency_notification.save
    #redirect back to the all notifications view
    redirect_to :action => 'list'

#---------------------Sending Notification To GCM using "gcm" gem-------------------------------------------------------
	#set GCM ID for gem
	gcm = GCM.new("AIzaSyAEP2Sk1M2-aFax16by2LHozu1RWNoHE0c")

	#set what is sent in the notification
	options = {data:{title: @emergency_notification.title, message: @emergency_notification.message,
	notId:rand(1...1000)}, collapse_key: "updated_score", title: @emergency_notification.title}

	#Querying database for what users are authenticated
	authenticatedUsers = User.where(authenticated: true)

	#User device IDS to send the notification to
	registration_ids = authenticatedUsers.map {|u| u.deviceID}

	#Display IDS for debug purposes
	puts ["REGISTRATION ID = ", registration_ids]

	#Using GCM gem to send notification
	response = gcm.send(registration_ids, options)
#-----------------------------------------------------------------------------------------------------------------------
  end

  # POST /emergency_notifications_group
  # POST /emergency_notifications_group.json
  def createGroup
    #create new Notification with parameters passed in
    @emergency_notification = EmergencyNotification.new(emergency_notification_params)
    #print notification details to logs and console for debug purposes
  	logger.error(@emergency_notification.message)
  	logger.error(@emergency_notification.title)
  	logger.error(params[:group])
    #save notification
    @emergency_notification.save
    #redirect back to the all notifications view
    redirect_to :action => 'list'

#---------------------Sending Notification To GCM using "gcm" gem-------------------------------------------------------
	#set GCM ID for gem
	gcm = GCM.new("AIzaSyAEP2Sk1M2-aFax16by2LHozu1RWNoHE0c")

	#set what is sent in the notification
	options = {data:{title: @emergency_notification.title, message: @emergency_notification.message,
	notId:rand(1...1000)}, collapse_key: "updated_score", title: @emergency_notification.title}

	#retrieving the users group
	group = params[:group]

	#Querying database for what users are authenticated
	authenticatedUsers = User.where(authenticated: true, group: group)

	#User device IDS to send the notification to
	registration_ids = authenticatedUsers.map {|u| u.deviceID}

	#Display IDS for debug purposes
	puts ["REGISTRATION ID = ", registration_ids]

	#Using GCM gem to send notification
	response = gcm.send(registration_ids, options)
#-----------------------------------------------------------------------------------------------------------------------
  end

  # POST /emergency_notifications_region
  # POST /emergency_notifications_region.json
  def createRegion
    #create new Notification with parameters passed in
    @emergency_notification = EmergencyNotification.new(emergency_notification_params)
    #print notification details to logs and console for debug purposes
  	logger.error(@emergency_notification.message)
  	logger.error(@emergency_notification.title)
  	logger.error(params[:region])
    #save notification
    @emergency_notification.save
    #redirect back to the all notifications view
    redirect_to :action => 'list'

#---------------------Sending Notification To GCM using "gcm" gem-------------------------------------------------------
	#set GCM ID for gem
	gcm = GCM.new("AIzaSyAEP2Sk1M2-aFax16by2LHozu1RWNoHE0c")

	#set what is sent in the notification
	options = {data:{title: @emergency_notification.title, message: @emergency_notification.message,
	notId:rand(1...1000)}, collapse_key: "updated_score", title: @emergency_notification.title}

	#retrieving the users region
	region = params[:region]
  puts [region]
	#Querying database for what users are authenticated
	authenticatedUsers = User.where(authenticated: true, region: region)

	#User device IDS to send the notification to
	registration_ids = authenticatedUsers.map {|u| u.deviceID}

	#Display IDS for debug purposes
	puts ["REGISTRATION ID = ", registration_ids]

	#Using GCM gem to send notification
	response = gcm.send(registration_ids, options)
#-----------------------------------------------------------------------------------------------------------------------
  end

  # POST /emergency_notifications/countSuccess
  # POST /emergency_notifications/countSuccess.json
  def countSuccess
  	#When POST from app is received increment the confirmations counter on the last notification by +1
  	EmergencyNotification.last.increment!(:confirmations)
  end

  # PATCH/PUT /emergency_notifications/1
  # PATCH/PUT /emergency_notifications/1.json
  def update
    respond_to do |format|
      if @emergency_notification.update(emergency_notification_params)
        format.html { redirect_to @emergency_notification, notice: 'Emergency notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @emergency_notification }
      else
        format.html { render :edit }
        format.json { render json: @emergency_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergency_notifications/1
  # DELETE /emergency_notifications/1.json
  def destroy
    @emergency_notification.destroy
    respond_to do |format|
      format.html { redirect_to emergency_notifications_url, notice: 'Emergency notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency_notification
      @emergency_notification = EmergencyNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergency_notification_params
      params.require(:emergency_notification).permit(:title, :message)
    end
end

SDHB-Server-App/app/helpers/emergency_notifications_helper.rb
module EmergencyNotificationsHelper
end

SDHB-Server-App/app/views/emergency_notifications/_form.html.erb
<%= form_for(@emergency_notification) do |f| %>
  <% if @emergency_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emergency_notification.errors.count, "error") %> prohibited this emergency_notification from being saved:</h2>

      <ul>
      <% @emergency_notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SDHB-Server-App/app/views/emergency_notifications/edit.html.erb
<h1>Editing emergency_notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @emergency_notification %> |
<%= link_to 'Back', emergency_notifications_path %>

SDHB-Server-App/app/views/emergency_notifications/group.html.erb
<!--SEND GROUP NOTIFICATION VIEW-->
<html>
	<head>
		<title>Send Group Notification</title>
	</head>
	<body>
		<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/emergency_notifications_group">Send Group Notification</a>
					</li>
					<li>
						<a href="/emergency_notifications_region">Send Region Notification</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
					<li>
						<a href="/allnotifications">Previous Notifications</a>
					</li>
					<li>
						<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>
					</li>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
				<div id="main">
					<h1 class="jumbotron">Send a Group Notification</h1>
					<!--Send Notification Button-->
					<form action="/emergency_notifications_group" method="POST" class="form-horizontal">
						<h3>New Emergency</h3>
						<br>
						<%= select_tag "group", options_from_collection_for_select(User.all.to_a.uniq{ |o| o.group }, :group, :group)%>
						<br>
						<br>
						<div class="input-group" id="inputboxcenter">
							<span class="input-group-addon" id="sizing-addon1">Title</span>
							<input type="text" name="emergency_notification[title]" class="form-control" placeholder="Title" aria-describedby="sizing-addon1">
						</div>
						<br>
						<div class="input-group" id="inputboxcenter">
							<span class="input-group-addon" id="sizing-addon2">Description</span>
							<input type="textarea" name="emergency_notification[message]" class="form-control" placeholder="Description" aria-describedby="sizing-addon2">
						</div>
						<br>
						<button class="btn btn-primary" id="buttonsend">Send Emergency</button>
					</form>
				</div>
			</div>
			<!-- /#page-content-wrapper -->

		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}

		});
		</script>
	</body>
</html>

SDHB-Server-App/app/views/emergency_notifications/index.html.erb
<!--SEND NOTIFICATION VIEW-->
<html>
	<head>
		<title>Send Notification</title>
	</head>
	<body>
		<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/emergency_notifications_group">Send Group Notification</a>
					</li>
					<li>
						<a href="/emergency_notifications_region">Send Region Notification</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
					<li>
						<a href="/allnotifications">Previous Notifications</a>
					</li>
					<li>
						<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>
					</li>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
				<div id="main">
					<h1 class="jumbotron">Send a Notification</h1>
					<!--Send Notification Button-->
					<form action="/emergency_notifications" method="POST" class="form-horizontal">
						<h3>New Emergency</h3>
						<br>
						<div class="input-group" id="inputboxcenter">
							<span class="input-group-addon" id="sizing-addon1">Title</span>
							<input type="text" name="emergency_notification[title]" class="form-control" placeholder="Title" aria-describedby="sizing-addon1">
						</div>
						<br>
						<div class="input-group" id="inputboxcenter">
							<span class="input-group-addon" id="sizing-addon2">Description</span>
							<input type="textarea" name="emergency_notification[message]" class="form-control" placeholder="Description" aria-describedby="sizing-addon2">
						</div>
						<br>
						<button class="btn btn-primary" id="buttonsend">Send Emergency</button>
					</form>
				</div>
			</div>
			<!-- /#page-content-wrapper -->

		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}

		});
		</script>
	</body>
</html>

SDHB-Server-App/app/views/emergency_notifications/list.erb
<!--ALL NOTIFICATIONS VIEW-->
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title>All Users</title>
	</head>
	<body>
		<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/emergency_notifications_group">Send Group Notification</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
					<li>
						<a href="/allnotifications">Previous Notifications</a>
					</li>
					<li>
						<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>
					</li>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
			<h1 class="jumbotron">Previous Emergencies</h1>
			<table class="table table-striped">
			  <thead>
				<tr>
				  <th>Date Sent</th>
				  <th>Title</th>
				  <th>Description</th>
				  <th>Confirmations</th>
				  <th colspan="3"></th>
				</tr>
			  </thead>
			  <tbody>
				<% EmergencyNotification.all.each do |emergency_notification| %>
				  <tr>
					<td><%= emergency_notification.created_at %></td>
					<td><%= emergency_notification.title %></td>
					<td><%= emergency_notification.message %></td>
					<td><%= emergency_notification.confirmations %></td>
				  </tr>
				<% end %>
			  </tbody>
			</table>
			<br>
			<%= button_to "Clear Notifications", {:controller=>"emergency_notifications", :action => "clear_notifications"} , :method => "get" %>

			<!-- /#page-content-wrapper -->

		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}

		});
		</script>
	</body>
</html>

SDHB-Server-App/app/views/emergency_notifications/new.html.erb
<h1>New emergency_notification</h1>

<%= render 'form' %>

<%= link_to 'Back', emergency_notifications_path %>

SDHB-Server-App/app/views/emergency_notifications/region.erb
<!--SEND REGION NOTIFICATION VIEW-->
<html>
	<head>
		<title>Send Region Notification</title>
	</head>
	<body>
		<div id="wrapper">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<a href="/">
							Send Notification
						</a>
					</li>
					<li>
						<a href="/emergency_notifications_group">Send Group Notification</a>
					</li>
          <li>
						<a href="/emergency_notifications_region">Send Region Notification</a>
					</li>
					<li>
						<a href="/allusers">All Users</a>
					</li>
					<li>
						<a href="/allnotifications">Previous Notifications</a>
					</li>
					<li>
						<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>
					</li>
				</ul>
			</div>
			<!-- /#sidebar-wrapper -->
			<!-- Page Content -->
			<div id="page-content-wrapper">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span id="arrow" class="glyphicon glyphicon-chevron-left"></span></a>
						</div>
					</div>
				</div>
				<div id="main">
					<h1 class="jumbotron">Send a Regional Notification</h1>
					<!--Send Notification Button-->
					<form action="/emergency_notifications_region" method="POST" class="form-horizontal">
						<h3>New Emergency</h3>
						<br>
						<%= select_tag "region", options_from_collection_for_select(User.all.to_a.uniq{ |o| o.region }, :region, :region)%>
						<br>
						<br>
						<div class="input-group" id="inputboxcenter">
							<span class="input-group-addon" id="sizing-addon1">Title</span>
							<input type="text" name="emergency_notification[title]" class="form-control" placeholder="Title" aria-describedby="sizing-addon1">
						</div>
						<br>
						<div class="input-group" id="inputboxcenter">
							<span class="input-group-addon" id="sizing-addon2">Description</span>
							<input type="textarea" name="emergency_notification[message]" class="form-control" placeholder="Description" aria-describedby="sizing-addon2">
						</div>
						<br>
						<button class="btn btn-primary" id="buttonsend">Send Emergency</button>
					</form>
				</div>
			</div>
			<!-- /#page-content-wrapper -->

		</div>
		<!-- /#wrapper -->
		<!-- Menu Toggle Script -->
		<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
			//Created by Alexander McNeill
			if($("#wrapper").hasClass("toggled"))
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-right");
			}
			else
			{
				$("#arrow").attr('class', "glyphicon glyphicon-chevron-left");
			}

		});
		</script>
	</body>
</html>

SDHB-Server-App/app/views/emergency_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @emergency_notification.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @emergency_notification.message %>
</p>

<p>
  <strong>Confirmations:</strong>
  <%= @emergency_notification.confirmations %>
</p>

<%= link_to 'Edit', edit_emergency_notification_path(@emergency_notification) %> |
<%= link_to 'Back', emergency_notifications_path %>